<robot name="box_" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:property name="width" value="1" />
<xacro:property name="rad" value="0.1" />

<link name="base_link">
	    <visual>
	      <geometry>
	        <box size="${4*width} ${4*width} ${4*width}"/>
	      </geometry>
	    </visual>
	    
	    <collision>
	      <geometry>
	        <box size="${4*width} ${4*width} ${4*width}"/>
	      </geometry>
	    </collision>
	    
	    <inertial>
		    <origin xyz="0 0 0"/>
		    <mass value="10.0"/>
		    <inertia ixx="26.66" ixy="0" ixz="0" iyz="0" iyy="26.66" izz="26.66" />
		</inertial>
		
 </link>

<link name="base">
	    <visual>
	    <origin xyz="0 0 ${width/2}" />
	      <geometry>
	        <box size="${width} ${width} ${width}"/>
	      </geometry>
	    </visual>
	    
	    <collision>
	    <origin xyz="0 0 ${width/2}" />
	      <geometry>
	        <box size="${width} ${width} ${width}"/>
	      </geometry>
	    </collision>
	    
	    <inertial>
	    <origin xyz="0 0 ${width/2}" />
		    <origin xyz="0 0 0"/>
		    <mass value="0.01"/>
		    <inertia ixx="0.00166" ixy="0" ixz="0" iyz="0" iyy="0.00166" izz="0.00166" />
		</inertial>		
 </link>
 
 <link name="joint_helper">
	    <visual>
	    <origin xyz="0 0 0.05" />
	      <geometry>
	        <box size="0.05 0.05 0.05"/>
	      </geometry>
	    </visual>
	    
	    <collision>
	    <origin xyz="0 0 0.05}" />
	      <geometry>
	        <box size="0.05 0.05 0.05"/>
	      </geometry>
	    </collision>
	    
	    <inertial>
	    <origin xyz="0 0 0.05" />
		    <origin xyz="0 0 0"/>
		    <mass value="0.1"/>
		    <inertia ixx="0.000416" ixy="0" ixz="0" iyz="0" iyy="0.000416" izz="0.000416" />
		</inertial>
		
 </link>
	  
 <joint name="flap_joint_x" type="revolute">
	    	<origin xyz="0 0 ${2*width}" rpy="0 0 0"/>
	    	<limit effort="1000.0" lower="-1.57" upper="1.57" velocity="0.5"/>
	    	<dynamics friction="100"/>
          <axis xyz="1 0 0"/>
			<parent link="base_link" />
			<child link="joint_helper" />
</joint>

 <joint name="flap_joint_y" type="revolute">
	    	<origin xyz="0 0 0.1" rpy="0 0 0"/>
	    	<limit effort="1000.0" lower="-1.57" upper="1.57" velocity="0.5"/>
	    	<dynamics friction="100"/>
          <axis xyz="0 1 0"/>
			<parent link="joint_helper" />
			<child link="base" />
</joint>

 <link name="arm">
	  	<visual>
	  		<origin xyz="0 0 ${width/10}" />
	  		<geometry>
	  			<cylinder radius="${rad}" length="${width/5}" />
	  		</geometry>
	  	</visual>
	  	
	  	<collision>
	  		<origin xyz="0 0 ${width/10}" />
	      <geometry>
	       	<cylinder radius="${rad}" length="${width/5}" />
	      </geometry>
	    </collision>
	    
	    <inertial>
	    	<origin xyz="0 0 ${width/10}" />
		    <mass value="0.01"/>
		    <inertia ixx="0.0000583" ixy="0" ixz="0" iyz="0" iyy="0.0000583" izz="0.00000833" />
		</inertial>
		
</link>		
			
<joint name="boxToArm" type="continuous">
	    	<origin xyz="0 0 ${width}" rpy="0 0 0"/>
          <axis xyz="0 0 1"/>
			<parent link="base" />
			<child link="arm" />
</joint>

<link name="propeller">
	  	<visual>
	  	
	  		<geometry>
	  			<box size="${width} ${width/5} ${width/100}"/>
	  		</geometry>
	  	</visual>
	  	
	  	<collision>
          <geometry>
	        <box size="${width} ${width/5} ${width/100}"/>
	      </geometry>
	    </collision>
	    
	    <inertial>
		    <mass value="0.05"/>
		    <inertia ixx="0.00016" ixy="0" ixz="0" iyz="0" iyy=" 0.00416" izz="0.004" />
		</inertial>
		
</link>	

		
<joint name="armToPropeller" type="fixed">
	    	<origin xyz="0 0 0.2" />
          	<axis xyz="0 0 1"/>
			<parent link="arm" />
			<child link="propeller" />
</joint>
  
   <gazebo>
   		<plugin name="joint_plugin" filename="libbox_joint_lib.so"/>
   		<plugin name="box_thruster_driver_plugin" filename="libthruster_driver.so"/>
   		<plugin name="box_prop_plugin" filename="libprop_forcer.so"/>
   		<plugin name="box_body_drags_plugin" filename="libbody_drags.so"/>
   		 		
   	</gazebo>

  </robot>